[package]
name = "replacer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0"
rdev = { version = "0.5.1", features = ["serialize"] }
serde = "1.0.143"
serde_json = "1.0.83"
